import * as fc from 'fast-check';
import { CSVExportService } from '../csv-export.service';
import {
  ProfitLossReport,
  BalanceSheetReport,
  CashFlowReport
} from '../../../types/balance-reports';

/**
 * Property-Based Tests for CSV Export Service
 * 
 * Feature: billing-balance-reports
 * Validates: Requirements 8.2
 */

describe('CSVExportService - Property-Based Tests', () => {
  /**
   * Property 16: CSV Export Format
   * **Feature: billing-balance-reports, Property 16: CSV Export Format**
   * **Validates: Requirements 8.2**
   * 
   * For any valid report, the CSV export should:
   * 1. Include all required metadata (report type, date range, generated by, timestamp)
   * 2. Format currency values with 2 decimal places and thousand separators
   * 3. Format dates in YYYY-MM-DD format
   * 4. Include all report sections and data
   */
  describe('Property 16: CSV Export Format', () => {
    test('Profit & Loss CSV export includes all required metadata', () => {
      fc.assert(
        fc.property(
          fc.record({
            startDate: fc.constantFrom('2024-01-01', '2024-04-01', '2024-07-01'),
            endDate: fc.constantFrom('2024-03-31', '2024-06-30', '2024-12-31'),
            generatedBy: fc.string({ minLength: 3, maxLength: 50 }),
            revenue: fc.record({
              consultations: fc.float({ min: 0, max: 1000000 }),
              procedures: fc.float({ min: 0, max: 1000000 }),
              medications: fc.float({ min: 0, max: 1000000 }),
              labTests: fc.float({ min: 0, max: 1000000 }),
              other: fc.float({ min: 0, max: 1000000 })
            }),
            expenses: fc.record({
              salaries: fc.float({ min: 0, max: 1000000 }),
              supplies: fc.float({ min: 0, max: 1000000 }),
              utilities: fc.float({ min: 0, max: 1000000 }),
              maintenance: fc.float({ min: 0, max: 1000000 }),
              other: fc.float({ min: 0, max: 1000000 })
            })
          }),
          ({ startDate, endDate, generatedBy, revenue, expenses }) => {
            const report: ProfitLossReport = {
              reportType: 'profit-loss',
              period: { startDate, endDate },
              revenue: {
                ...revenue,
                total: revenue.consultations + revenue.procedures + revenue.medications + revenue.labTests + revenue.other
              },
              expenses: {
                ...expenses,
                total: expenses.salaries + expenses.supplies + expenses.utilities + expenses.maintenance + expenses.other
              },
              netProfitLoss: (revenue.consultations + revenue.procedures + revenue.medications + revenue.labTests + revenue.other) -
                            (expenses.salaries + expenses.supplies + expenses.utilities + expenses.maintenance + expenses.other),
              generatedAt: new Date().toISOString(),
              generatedBy
            };

            const csv = CSVExportService.exportToCSV(report, 'profit-loss');

            // Property: CSV must include report type
            expect(csv).toContain('Profit & Loss Report');

            // Property: CSV must include date range
            expect(csv).toContain(startDate);
            expect(csv).toContain(endDate);

            // Property: CSV must include generated by
            expect(csv).toContain(generatedBy);

            // Property: CSV must include all revenue categories
            expect(csv).toContain('REVENUE');
            expect(csv).toContain('Consultations');
            expect(csv).toContain('Procedures');
            expect(csv).toContain('Medications');
            expect(csv).toContain('Lab Tests');

            // Property: CSV must include all expense categories
            expect(csv).toContain('EXPENSES');
            expect(csv).toContain('Salaries');
            expect(csv).toContain('Supplies');
            expect(csv).toContain('Utilities');
            expect(csv).toContain('Maintenance');

            // Property: CSV must include summary
            expect(csv).toContain('SUMMARY');
            expect(csv).toContain('Net Profit/Loss');
          }
        ),
        { numRuns: 100 }
      );
    });

    test('Balance Sheet CSV export includes all required sections', () => {
      fc.assert(
        fc.property(
          fc.record({
            asOfDate: fc.constantFrom('2024-01-01', '2024-06-30', '2024-12-31'),
            generatedBy: fc.string({ minLength: 3, maxLength: 50 }),
            currentAssets: fc.record({
              cash: fc.float({ min: 0, max: 1000000 }),
              accountsReceivable: fc.float({ min: 0, max: 1000000 }),
              inventory: fc.float({ min: 0, max: 1000000 })
            }),
            fixedAssets: fc.record({
              equipment: fc.float({ min: 0, max: 1000000 }),
              buildings: fc.float({ min: 0, max: 1000000 }),
              land: fc.float({ min: 0, max: 1000000 }),
              vehicles: fc.float({ min: 0, max: 1000000 })
            }),
            currentLiabilities: fc.record({
              accountsPayable: fc.float({ min: 0, max: 1000000 }),
              accruedExpenses: fc.float({ min: 0, max: 1000000 })
            }),
            longTermLiabilities: fc.record({
              loans: fc.float({ min: 0, max: 1000000 }),
              mortgages: fc.float({ min: 0, max: 1000000 })
            })
          }),
          ({ asOfDate, generatedBy, currentAssets, fixedAssets, currentLiabilities, longTermLiabilities }) => {
            const currentAssetsTotal = currentAssets.cash + currentAssets.accountsReceivable + currentAssets.inventory;
            const fixedAssetsTotal = fixedAssets.equipment + fixedAssets.buildings + fixedAssets.land + fixedAssets.vehicles;
            const assetsTotal = currentAssetsTotal + fixedAssetsTotal;
            
            const currentLiabilitiesTotal = currentLiabilities.accountsPayable + currentLiabilities.accruedExpenses;
            const longTermLiabilitiesTotal = longTermLiabilities.loans + longTermLiabilities.mortgages;
            const liabilitiesTotal = currentLiabilitiesTotal + longTermLiabilitiesTotal;
            
            const equityTotal = assetsTotal - liabilitiesTotal;

            const report: BalanceSheetReport = {
              reportType: 'balance-sheet',
              asOfDate,
              assets: {
                current: {
                  ...currentAssets,
                  total: currentAssetsTotal
                },
                fixed: {
                  ...fixedAssets,
                  total: fixedAssetsTotal
                },
                total: assetsTotal
              },
              liabilities: {
                current: {
                  ...currentLiabilities,
                  total: currentLiabilitiesTotal
                },
                longTerm: {
                  ...longTermLiabilities,
                  total: longTermLiabilitiesTotal
                },
                total: liabilitiesTotal
              },
              equity: {
                retainedEarnings: equityTotal,
                total: equityTotal
              },
              accountingEquationBalanced: Math.abs(assetsTotal - (liabilitiesTotal + equityTotal)) < 0.01,
              generatedAt: new Date().toISOString(),
              generatedBy
            };

            const csv = CSVExportService.exportToCSV(report, 'balance-sheet');

            // Property: CSV must include report type
            expect(csv).toContain('Balance Sheet Report');

            // Property: CSV must include as of date
            expect(csv).toContain(asOfDate);

            // Property: CSV must include assets section
            expect(csv).toContain('ASSETS');
            expect(csv).toContain('Current Assets');
            expect(csv).toContain('Fixed Assets');
            expect(csv).toContain('Cash');
            expect(csv).toContain('Equipment');

            // Property: CSV must include liabilities section
            expect(csv).toContain('LIABILITIES');
            expect(csv).toContain('Current Liabilities');
            expect(csv).toContain('Long-term Liabilities');

            // Property: CSV must include equity section
            expect(csv).toContain('EQUITY');

            // Property: CSV must include accounting equation
            expect(csv).toContain('ACCOUNTING EQUATION');
          }
        ),
        { numRuns: 100 }
      );
    });

    test('Cash Flow CSV export includes all activity sections', () => {
      fc.assert(
        fc.property(
          fc.record({
            startDate: fc.constantFrom('2024-01-01', '2024-04-01', '2024-07-01'),
            endDate: fc.constantFrom('2024-03-31', '2024-06-30', '2024-12-31'),
            generatedBy: fc.string({ minLength: 3, maxLength: 50 }),
            operatingInflows: fc.float({ min: 0, max: 1000000 }),
            operatingOutflows: fc.float({ min: 0, max: 1000000 }),
            investingInflows: fc.float({ min: 0, max: 1000000 }),
            investingOutflows: fc.float({ min: 0, max: 1000000 }),
            financingInflows: fc.float({ min: 0, max: 1000000 }),
            financingOutflows: fc.float({ min: 0, max: 1000000 }),
            beginningCash: fc.float({ min: 0, max: 1000000 })
          }),
          ({ startDate, endDate, generatedBy, operatingInflows, operatingOutflows, 
             investingInflows, investingOutflows, financingInflows, financingOutflows, beginningCash }) => {
            
            const operatingNet = operatingInflows - operatingOutflows;
            const investingNet = investingInflows - investingOutflows;
            const financingNet = financingInflows - financingOutflows;
            const netCashFlow = operatingNet + investingNet + financingNet;

            const report: CashFlowReport = {
              reportType: 'cash-flow',
              period: { startDate, endDate },
              operatingActivities: {
                inflows: { patientPayments: operatingInflows, insuranceReimbursements: 0, other: 0, total: operatingInflows },
                outflows: { salaries: operatingOutflows, supplies: 0, utilities: 0, equipmentPurchases: 0, loanRepayments: 0, other: 0, total: operatingOutflows },
                net: operatingNet
              },
              investingActivities: {
                inflows: { patientPayments: investingInflows, insuranceReimbursements: 0, other: 0, total: investingInflows },
                outflows: { salaries: investingOutflows, supplies: 0, utilities: 0, equipmentPurchases: 0, loanRepayments: 0, other: 0, total: investingOutflows },
                net: investingNet
              },
              financingActivities: {
                inflows: { patientPayments: financingInflows, insuranceReimbursements: 0, other: 0, total: financingInflows },
                outflows: { salaries: financingOutflows, supplies: 0, utilities: 0, equipmentPurchases: 0, loanRepayments: 0, other: 0, total: financingOutflows },
                net: financingNet
              },
              netCashFlow,
              beginningCash,
              endingCash: beginningCash + netCashFlow,
              generatedAt: new Date().toISOString(),
              generatedBy
            };

            const csv = CSVExportService.exportToCSV(report, 'cash-flow');

            // Property: CSV must include report type
            expect(csv).toContain('Cash Flow Report');

            // Property: CSV must include date range
            expect(csv).toContain(startDate);
            expect(csv).toContain(endDate);

            // Property: CSV must include all activity sections
            expect(csv).toContain('OPERATING ACTIVITIES');
            expect(csv).toContain('INVESTING ACTIVITIES');
            expect(csv).toContain('FINANCING ACTIVITIES');

            // Property: CSV must include summary
            expect(csv).toContain('SUMMARY');
            expect(csv).toContain('Beginning Cash Balance');
            expect(csv).toContain('Ending Cash Balance');
            expect(csv).toContain('Total Net Cash Flow');
          }
        ),
        { numRuns: 100 }
      );
    });

    test('Currency values are formatted with 2 decimal places', () => {
      fc.assert(
        fc.property(
          fc.float({ min: 0, max: 1000000 }),
          (amount) => {
            const report: ProfitLossReport = {
              reportType: 'profit-loss',
              period: { startDate: '2024-01-01', endDate: '2024-12-31' },
              revenue: {
                consultations: amount,
                procedures: 0,
                medications: 0,
                labTests: 0,
                other: 0,
                total: amount
              },
              expenses: {
                salaries: 0,
                supplies: 0,
                utilities: 0,
                maintenance: 0,
                other: 0,
                total: 0
              },
              netProfitLoss: amount,
              generatedAt: new Date().toISOString(),
              generatedBy: 'test'
            };

            const csv = CSVExportService.exportToCSV(report, 'profit-loss');

            // Property: All currency values should have exactly 2 decimal places
            const formattedAmount = amount.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
            expect(csv).toContain(formattedAmount);
          }
        ),
        { numRuns: 100 }
      );
    });

    test('Filename generation includes report type and date', () => {
      fc.assert(
        fc.property(
          fc.record({
            reportType: fc.constantFrom('profit-loss', 'balance-sheet', 'cash-flow'),
            startDate: fc.constantFrom('2024-01-01', '2024-04-01', '2024-07-01'),
            endDate: fc.constantFrom('2024-03-31', '2024-06-30', '2024-12-31')
          }),
          ({ reportType, startDate, endDate }) => {
            const filename = CSVExportService.getFilename(reportType, startDate, endDate);

            // Property: Filename must include report type
            expect(filename).toContain(reportType);

            // Property: Filename must include date range
            expect(filename).toContain(startDate);
            expect(filename).toContain(endDate);

            // Property: Filename must have .csv extension
            expect(filename).toMatch(/\.csv$/);
          }
        ),
        { numRuns: 100 }
      );
    });
  });
});
