/**
 * Property-Based Tests for Export Metadata Inclusion
 * 
 * **Feature: billing-balance-reports, Property 17: Export Metadata Inclusion**
 * **Validates: Requirements 8.5**
 * 
 * Tests that all exported reports include required metadata:
 * - Report type
 * - Date information (period or as-of date)
 * - Generated by (user)
 * - Generated at (timestamp)
 */

import * as fc from 'fast-check';
import { CSVExportService } from '../csv-export.service';
import { ExcelExportService } from '../excel-export.service';
import { PDFExportService } from '../pdf-export.service';
import {
  ProfitLossReport,
  BalanceSheetReport,
  CashFlowReport
} from '../../../types/balance-reports';

describe('Export Metadata Inclusion - Property Tests', () => {
  // Helper to generate valid date strings
  const dateStringArb = fc.constantFrom(
    '2024-01-01', '2024-03-31', '2024-06-30', '2024-09-30', '2024-12-31',
    '2023-01-01', '2023-06-30', '2023-12-31'
  );

  const timestampArb = fc.constantFrom(
    '2024-01-15T10:30:00.000Z',
    '2024-06-20T14:45:00.000Z',
    '2024-11-30T09:00:00.000Z'
  );

  const generatedByArb = fc.constantFrom(
    'John Smith', 'Jane Doe', 'Admin User', 'Finance Manager', 
    'Hospital Admin', 'System User', 'Report Generator'
  );

  /**
   * Generate a valid Profit & Loss report
   */
  const profitLossReportArb = fc.record({
    reportType: fc.constant('profit-loss' as const),
    period: fc.record({
      startDate: dateStringArb,
      endDate: dateStringArb
    }),
    departmentId: fc.option(fc.integer({ min: 1, max: 100 }), { nil: undefined }),
    revenue: fc.record({
      consultations: fc.float({ min: 0, max: 1000000, noNaN: true }),
      procedures: fc.float({ min: 0, max: 1000000, noNaN: true }),
      medications: fc.float({ min: 0, max: 1000000, noNaN: true }),
      labTests: fc.float({ min: 0, max: 1000000, noNaN: true }),
      other: fc.float({ min: 0, max: 1000000, noNaN: true }),
      total: fc.float({ min: 0, max: 5000000, noNaN: true })
    }),
    expenses: fc.record({
      salaries: fc.float({ min: 0, max: 1000000, noNaN: true }),
      supplies: fc.float({ min: 0, max: 1000000, noNaN: true }),
      utilities: fc.float({ min: 0, max: 1000000, noNaN: true }),
      maintenance: fc.float({ min: 0, max: 1000000, noNaN: true }),
      other: fc.float({ min: 0, max: 1000000, noNaN: true }),
      total: fc.float({ min: 0, max: 5000000, noNaN: true })
    }),
    netProfitLoss: fc.float({ min: -5000000, max: 5000000, noNaN: true }),
    generatedAt: timestampArb,
    generatedBy: generatedByArb
  }) as fc.Arbitrary<ProfitLossReport>;

  /**
   * Generate a valid Balance Sheet report
   */
  const balanceSheetReportArb = fc.record({
    reportType: fc.constant('balance-sheet' as const),
    asOfDate: dateStringArb,
    departmentId: fc.option(fc.integer({ min: 1, max: 100 }), { nil: undefined }),
    assets: fc.record({
      current: fc.record({
        cash: fc.float({ min: 0, max: 1000000, noNaN: true }),
        accountsReceivable: fc.float({ min: 0, max: 1000000, noNaN: true }),
        inventory: fc.float({ min: 0, max: 1000000, noNaN: true }),
        total: fc.float({ min: 0, max: 3000000, noNaN: true })
      }),
      fixed: fc.record({
        equipment: fc.float({ min: 0, max: 1000000, noNaN: true }),
        buildings: fc.float({ min: 0, max: 5000000, noNaN: true }),
        land: fc.float({ min: 0, max: 5000000, noNaN: true }),
        vehicles: fc.float({ min: 0, max: 500000, noNaN: true }),
        total: fc.float({ min: 0, max: 11500000, noNaN: true })
      }),
      total: fc.float({ min: 0, max: 15000000, noNaN: true })
    }),
    liabilities: fc.record({
      current: fc.record({
        accountsPayable: fc.float({ min: 0, max: 1000000, noNaN: true }),
        accruedExpenses: fc.float({ min: 0, max: 500000, noNaN: true }),
        total: fc.float({ min: 0, max: 1500000, noNaN: true })
      }),
      longTerm: fc.record({
        loans: fc.float({ min: 0, max: 5000000, noNaN: true }),
        mortgages: fc.float({ min: 0, max: 5000000, noNaN: true }),
        total: fc.float({ min: 0, max: 10000000, noNaN: true })
      }),
      total: fc.float({ min: 0, max: 11500000, noNaN: true })
    }),
    equity: fc.record({
      retainedEarnings: fc.float({ min: -5000000, max: 10000000, noNaN: true }),
      total: fc.float({ min: -5000000, max: 10000000, noNaN: true })
    }),
    accountingEquationBalanced: fc.boolean(),
    generatedAt: timestampArb,
    generatedBy: generatedByArb
  }) as fc.Arbitrary<BalanceSheetReport>;

  /**
   * Generate a valid Cash Flow report
   */
  const cashFlowReportArb = fc.record({
    reportType: fc.constant('cash-flow' as const),
    period: fc.record({
      startDate: dateStringArb,
      endDate: dateStringArb
    }),
    departmentId: fc.option(fc.integer({ min: 1, max: 100 }), { nil: undefined }),
    operatingActivities: fc.record({
      inflows: fc.record({
        patientPayments: fc.float({ min: 0, max: 1000000, noNaN: true }),
        insuranceReimbursements: fc.float({ min: 0, max: 1000000, noNaN: true }),
        other: fc.float({ min: 0, max: 500000, noNaN: true }),
        total: fc.float({ min: 0, max: 2500000, noNaN: true })
      }),
      outflows: fc.record({
        salaries: fc.float({ min: 0, max: 1000000, noNaN: true }),
        supplies: fc.float({ min: 0, max: 500000, noNaN: true }),
        utilities: fc.float({ min: 0, max: 200000, noNaN: true }),
        equipmentPurchases: fc.float({ min: 0, max: 500000, noNaN: true }),
        loanRepayments: fc.float({ min: 0, max: 500000, noNaN: true }),
        other: fc.float({ min: 0, max: 300000, noNaN: true }),
        total: fc.float({ min: 0, max: 3000000, noNaN: true })
      }),
      net: fc.float({ min: -3000000, max: 2500000, noNaN: true })
    }),
    investingActivities: fc.record({
      inflows: fc.record({
        patientPayments: fc.constant(0),
        insuranceReimbursements: fc.constant(0),
        other: fc.float({ min: 0, max: 500000, noNaN: true }),
        total: fc.float({ min: 0, max: 500000, noNaN: true })
      }),
      outflows: fc.record({
        salaries: fc.constant(0),
        supplies: fc.constant(0),
        utilities: fc.constant(0),
        equipmentPurchases: fc.float({ min: 0, max: 1000000, noNaN: true }),
        loanRepayments: fc.constant(0),
        other: fc.float({ min: 0, max: 500000, noNaN: true }),
        total: fc.float({ min: 0, max: 1500000, noNaN: true })
      }),
      net: fc.float({ min: -1500000, max: 500000, noNaN: true })
    }),
    financingActivities: fc.record({
      inflows: fc.record({
        patientPayments: fc.constant(0),
        insuranceReimbursements: fc.constant(0),
        other: fc.float({ min: 0, max: 1000000, noNaN: true }),
        total: fc.float({ min: 0, max: 1000000, noNaN: true })
      }),
      outflows: fc.record({
        salaries: fc.constant(0),
        supplies: fc.constant(0),
        utilities: fc.constant(0),
        equipmentPurchases: fc.constant(0),
        loanRepayments: fc.float({ min: 0, max: 500000, noNaN: true }),
        other: fc.float({ min: 0, max: 500000, noNaN: true }),
        total: fc.float({ min: 0, max: 1000000, noNaN: true })
      }),
      net: fc.float({ min: -1000000, max: 1000000, noNaN: true })
    }),
    netCashFlow: fc.float({ min: -5000000, max: 5000000, noNaN: true }),
    beginningCash: fc.float({ min: 0, max: 5000000, noNaN: true }),
    endingCash: fc.float({ min: 0, max: 10000000, noNaN: true }),
    generatedAt: timestampArb,
    generatedBy: generatedByArb
  }) as fc.Arbitrary<CashFlowReport>;

  describe('CSV Export Metadata', () => {
    /**
     * Property 17: CSV Export includes all required metadata
     * For any valid report, the CSV export must include:
     * - Report type/title
     * - Date information (period or as-of date)
     * - Generated at timestamp
     * - Generated by user
     */
    it('should include all required metadata in Profit & Loss CSV export', () => {
      fc.assert(
        fc.property(profitLossReportArb, (report) => {
          const csv = CSVExportService.exportToCSV(report, 'profit-loss');
          
          // Check for report title
          expect(csv).toContain('Profit & Loss Report');
          
          // Check for period dates
          expect(csv).toContain(report.period.startDate);
          expect(csv).toContain(report.period.endDate);
          
          // Check for generated at timestamp
          expect(csv).toContain('Generated At');
          
          // Check for generated by
          expect(csv).toContain('Generated By');
          expect(csv).toContain(report.generatedBy);
        }),
        { numRuns: 100 }
      );
    });

    it('should include all required metadata in Balance Sheet CSV export', () => {
      fc.assert(
        fc.property(balanceSheetReportArb, (report) => {
          const csv = CSVExportService.exportToCSV(report, 'balance-sheet');
          
          // Check for report title
          expect(csv).toContain('Balance Sheet Report');
          
          // Check for as-of date
          expect(csv).toContain('As of Date');
          expect(csv).toContain(report.asOfDate);
          
          // Check for generated at timestamp
          expect(csv).toContain('Generated At');
          
          // Check for generated by
          expect(csv).toContain('Generated By');
          expect(csv).toContain(report.generatedBy);
        }),
        { numRuns: 100 }
      );
    });

    it('should include all required metadata in Cash Flow CSV export', () => {
      fc.assert(
        fc.property(cashFlowReportArb, (report) => {
          const csv = CSVExportService.exportToCSV(report, 'cash-flow');
          
          // Check for report title
          expect(csv).toContain('Cash Flow Report');
          
          // Check for period dates
          expect(csv).toContain(report.period.startDate);
          expect(csv).toContain(report.period.endDate);
          
          // Check for generated at timestamp
          expect(csv).toContain('Generated At');
          
          // Check for generated by
          expect(csv).toContain('Generated By');
          expect(csv).toContain(report.generatedBy);
        }),
        { numRuns: 100 }
      );
    });
  });

  describe('Excel Export Metadata', () => {
    /**
     * Property 17: Excel Export includes all required metadata
     */
    it('should include all required metadata in Profit & Loss Excel export', () => {
      fc.assert(
        fc.property(profitLossReportArb, (report) => {
          const excel = ExcelExportService.exportToExcel(report, 'profit-loss');
          
          // Check for report title (XML escaped)
          expect(excel).toContain('Profit &amp; Loss Report');
          
          // Check for Hospital Management System branding
          expect(excel).toContain('Hospital Management System');
          
          // Check for generated by (XML escaped)
          const generatedBy = report.generatedBy || '';
          const escapedGeneratedBy = generatedBy
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;');
          expect(excel).toContain(escapedGeneratedBy);
        }),
        { numRuns: 100 }
      );
    });

    it('should include all required metadata in Balance Sheet Excel export', () => {
      fc.assert(
        fc.property(balanceSheetReportArb, (report) => {
          const excel = ExcelExportService.exportToExcel(report, 'balance-sheet');
          
          // Check for report title
          expect(excel).toContain('Balance Sheet Report');
          
          // Check for Hospital Management System branding
          expect(excel).toContain('Hospital Management System');
          
          // Check for generated by (XML escaped)
          const generatedBy = report.generatedBy || '';
          const escapedGeneratedBy = generatedBy
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;');
          expect(excel).toContain(escapedGeneratedBy);
        }),
        { numRuns: 100 }
      );
    });

    it('should include all required metadata in Cash Flow Excel export', () => {
      fc.assert(
        fc.property(cashFlowReportArb, (report) => {
          const excel = ExcelExportService.exportToExcel(report, 'cash-flow');
          
          // Check for report title
          expect(excel).toContain('Cash Flow Report');
          
          // Check for Hospital Management System branding
          expect(excel).toContain('Hospital Management System');
          
          // Check for generated by (XML escaped)
          const generatedBy = report.generatedBy || '';
          const escapedGeneratedBy = generatedBy
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;');
          expect(excel).toContain(escapedGeneratedBy);
        }),
        { numRuns: 100 }
      );
    });
  });

  describe('PDF Export Metadata', () => {
    /**
     * Property 17: PDF Export includes all required metadata
     */
    it('should include all required metadata in Profit & Loss PDF export', () => {
      fc.assert(
        fc.property(profitLossReportArb, (report) => {
          const pdf = PDFExportService.exportToPDF(report, 'profit-loss');
          
          // Check for report title (HTML format)
          expect(pdf).toContain('Profit & Loss Report');
          
          // Check for Hospital Management System branding
          expect(pdf).toContain('Hospital Management System');
          
          // Check for generated by
          expect(pdf).toContain(report.generatedBy);
        }),
        { numRuns: 100 }
      );
    });

    it('should include all required metadata in Balance Sheet PDF export', () => {
      fc.assert(
        fc.property(balanceSheetReportArb, (report) => {
          const pdf = PDFExportService.exportToPDF(report, 'balance-sheet');
          
          // Check for report title
          expect(pdf).toContain('Balance Sheet Report');
          
          // Check for Hospital Management System branding
          expect(pdf).toContain('Hospital Management System');
          
          // Check for generated by
          expect(pdf).toContain(report.generatedBy);
        }),
        { numRuns: 100 }
      );
    });

    it('should include all required metadata in Cash Flow PDF export', () => {
      fc.assert(
        fc.property(cashFlowReportArb, (report) => {
          const pdf = PDFExportService.exportToPDF(report, 'cash-flow');
          
          // Check for report title
          expect(pdf).toContain('Cash Flow Report');
          
          // Check for Hospital Management System branding
          expect(pdf).toContain('Hospital Management System');
          
          // Check for generated by
          expect(pdf).toContain(report.generatedBy);
        }),
        { numRuns: 100 }
      );
    });
  });

  describe('Export Filename Generation', () => {
    /**
     * Property: Filenames should include report type and date information
     */
    it('should generate proper filenames for CSV exports', () => {
      fc.assert(
        fc.property(
          fc.constantFrom('profit-loss', 'balance-sheet', 'cash-flow'),
          dateStringArb,
          dateStringArb,
          (reportType, startDate, endDate) => {
            const filename = CSVExportService.getFilename(reportType, startDate, endDate);
            
            expect(filename).toContain(reportType);
            expect(filename).toContain(startDate);
            expect(filename).toContain(endDate);
            expect(filename.endsWith('.csv')).toBe(true);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should generate proper filenames for Excel exports', () => {
      fc.assert(
        fc.property(
          fc.constantFrom('profit-loss', 'balance-sheet', 'cash-flow'),
          dateStringArb,
          dateStringArb,
          (reportType, startDate, endDate) => {
            const filename = ExcelExportService.getFilename(reportType, startDate, endDate);
            
            expect(filename).toContain(reportType);
            expect(filename).toContain(startDate);
            expect(filename).toContain(endDate);
            expect(filename.endsWith('.xls')).toBe(true);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should generate proper filenames for PDF exports', () => {
      fc.assert(
        fc.property(
          fc.constantFrom('profit-loss', 'balance-sheet', 'cash-flow'),
          dateStringArb,
          dateStringArb,
          (reportType, startDate, endDate) => {
            const filename = PDFExportService.getFilename(reportType, startDate, endDate);
            
            expect(filename).toContain(reportType);
            expect(filename).toContain(startDate);
            expect(filename).toContain(endDate);
            expect(filename.endsWith('.pdf')).toBe(true);
          }
        ),
        { numRuns: 100 }
      );
    });
  });
});
