/**
 * CSV Export Service
 * 
 * Exports balance reports to CSV format with proper formatting
 * and Excel compatibility (UTF-8 BOM).
 * 
 * Requirements: 8.1, 8.2, 8.5
 */

import {
  ProfitLossReport,
  BalanceSheetReport,
  CashFlowReport
} from '../../types/balance-reports';

export class CSVExportService {
  /**
   * Export report to CSV format
   * 
   * @param report - Report data to export
   * @param reportType - Type of report
   * @returns CSV string with UTF-8 BOM
   */
  static exportToCSV(
    report: ProfitLossReport | BalanceSheetReport | CashFlowReport,
    reportType: 'profit-loss' | 'balance-sheet' | 'cash-flow'
  ): string {
    switch (reportType) {
      case 'profit-loss':
        return this.exportProfitLossToCSV(report as ProfitLossReport);
      case 'balance-sheet':
        return this.exportBalanceSheetToCSV(report as BalanceSheetReport);
      case 'cash-flow':
        return this.exportCashFlowToCSV(report as CashFlowReport);
      default:
        throw new Error(`Unsupported report type: ${reportType}`);
    }
  }

  /**
   * Export Profit & Loss report to CSV
   */
  private static exportProfitLossToCSV(report: ProfitLossReport): string {
    const lines: string[] = [];

    // Metadata rows
    lines.push('Profit & Loss Report');
    lines.push(`Period,${this.formatDate(report.period.startDate)} to ${this.formatDate(report.period.endDate)}`);
    lines.push(`Generated At,${this.formatDateTime(report.generatedAt)}`);
    lines.push(`Generated By,${report.generatedBy}`);
    if (report.departmentId) {
      lines.push(`Department,${report.departmentId}`);
    }
    lines.push(''); // Empty line

    // Revenue section
    lines.push('REVENUE');
    lines.push('Category,Amount');
    lines.push(`Consultations,${this.formatCurrency(report.revenue.consultations)}`);
    lines.push(`Procedures,${this.formatCurrency(report.revenue.procedures)}`);
    lines.push(`Medications,${this.formatCurrency(report.revenue.medications)}`);
    lines.push(`Lab Tests,${this.formatCurrency(report.revenue.labTests)}`);
    lines.push(`Other,${this.formatCurrency(report.revenue.other)}`);
    lines.push(`Total Revenue,${this.formatCurrency(report.revenue.total)}`);
    lines.push(''); // Empty line

    // Expenses section
    lines.push('EXPENSES');
    lines.push('Category,Amount');
    lines.push(`Salaries,${this.formatCurrency(report.expenses.salaries)}`);
    lines.push(`Supplies,${this.formatCurrency(report.expenses.supplies)}`);
    lines.push(`Utilities,${this.formatCurrency(report.expenses.utilities)}`);
    lines.push(`Maintenance,${this.formatCurrency(report.expenses.maintenance)}`);
    lines.push(`Other,${this.formatCurrency(report.expenses.other)}`);
    lines.push(`Total Expenses,${this.formatCurrency(report.expenses.total)}`);
    lines.push(''); // Empty line

    // Net Profit/Loss
    lines.push('SUMMARY');
    lines.push('Metric,Amount');
    lines.push(`Total Revenue,${this.formatCurrency(report.revenue.total)}`);
    lines.push(`Total Expenses,${this.formatCurrency(report.expenses.total)}`);
    lines.push(`Net Profit/Loss,${this.formatCurrency(report.netProfitLoss)}`);

    // Comparison data if available
    if (report.comparison) {
      lines.push(''); // Empty line
      lines.push('COMPARISON');
      lines.push('Metric,Current,Previous,Variance,Variance %');
      
      if (report.comparison.revenue) {
        lines.push(`Revenue,${this.formatCurrency(report.comparison.revenue.current)},${this.formatCurrency(report.comparison.revenue.previous)},${this.formatCurrency(report.comparison.revenue.variance)},${this.formatPercentage(report.comparison.revenue.variancePercent)}`);
      }
      
      if (report.comparison.expenses) {
        lines.push(`Expenses,${this.formatCurrency(report.comparison.expenses.current)},${this.formatCurrency(report.comparison.expenses.previous)},${this.formatCurrency(report.comparison.expenses.variance)},${this.formatPercentage(report.comparison.expenses.variancePercent)}`);
      }
      
      if (report.comparison.netProfitLoss) {
        lines.push(`Net Profit/Loss,${this.formatCurrency(report.comparison.netProfitLoss.current)},${this.formatCurrency(report.comparison.netProfitLoss.previous)},${this.formatCurrency(report.comparison.netProfitLoss.variance)},${this.formatPercentage(report.comparison.netProfitLoss.variancePercent)}`);
      }
    }

    return lines.join('\n');
  }

  /**
   * Export Balance Sheet report to CSV
   */
  private static exportBalanceSheetToCSV(report: BalanceSheetReport): string {
    const lines: string[] = [];

    // Metadata rows
    lines.push('Balance Sheet Report');
    lines.push(`As of Date,${this.formatDate(report.asOfDate)}`);
    lines.push(`Generated At,${this.formatDateTime(report.generatedAt)}`);
    lines.push(`Generated By,${report.generatedBy}`);
    if (report.departmentId) {
      lines.push(`Department,${report.departmentId}`);
    }
    lines.push(''); // Empty line

    // Assets section
    lines.push('ASSETS');
    lines.push('Category,Type,Amount');
    
    // Current Assets
    lines.push('Current Assets');
    lines.push(`Cash,Current,${this.formatCurrency(report.assets.current.cash)}`);
    lines.push(`Accounts Receivable,Current,${this.formatCurrency(report.assets.current.accountsReceivable)}`);
    lines.push(`Inventory,Current,${this.formatCurrency(report.assets.current.inventory)}`);
    lines.push(`Total Current Assets,,${this.formatCurrency(report.assets.current.total)}`);
    lines.push(''); // Empty line
    
    // Fixed Assets
    lines.push('Fixed Assets');
    lines.push(`Equipment,Fixed,${this.formatCurrency(report.assets.fixed.equipment)}`);
    lines.push(`Buildings,Fixed,${this.formatCurrency(report.assets.fixed.buildings)}`);
    lines.push(`Land,Fixed,${this.formatCurrency(report.assets.fixed.land)}`);
    lines.push(`Vehicles,Fixed,${this.formatCurrency(report.assets.fixed.vehicles)}`);
    lines.push(`Total Fixed Assets,,${this.formatCurrency(report.assets.fixed.total)}`);
    lines.push(''); // Empty line
    
    lines.push(`TOTAL ASSETS,,${this.formatCurrency(report.assets.total)}`);
    lines.push(''); // Empty line

    // Liabilities section
    lines.push('LIABILITIES');
    lines.push('Category,Type,Amount');
    
    // Current Liabilities
    lines.push('Current Liabilities');
    lines.push(`Accounts Payable,Current,${this.formatCurrency(report.liabilities.current.accountsPayable)}`);
    lines.push(`Accrued Expenses,Current,${this.formatCurrency(report.liabilities.current.accruedExpenses)}`);
    lines.push(`Total Current Liabilities,,${this.formatCurrency(report.liabilities.current.total)}`);
    lines.push(''); // Empty line
    
    // Long-term Liabilities
    lines.push('Long-term Liabilities');
    lines.push(`Loans,Long-term,${this.formatCurrency(report.liabilities.longTerm.loans)}`);
    lines.push(`Mortgages,Long-term,${this.formatCurrency(report.liabilities.longTerm.mortgages)}`);
    lines.push(`Total Long-term Liabilities,,${this.formatCurrency(report.liabilities.longTerm.total)}`);
    lines.push(''); // Empty line
    
    lines.push(`TOTAL LIABILITIES,,${this.formatCurrency(report.liabilities.total)}`);
    lines.push(''); // Empty line

    // Equity section
    lines.push('EQUITY');
    lines.push(`Retained Earnings,,${this.formatCurrency(report.equity.retainedEarnings)}`);
    lines.push(`Total Equity,,${this.formatCurrency(report.equity.total)}`);
    lines.push(''); // Empty line

    // Accounting equation
    lines.push('ACCOUNTING EQUATION');
    lines.push('Metric,Amount');
    lines.push(`Total Assets,${this.formatCurrency(report.assets.total)}`);
    lines.push(`Total Liabilities,${this.formatCurrency(report.liabilities.total)}`);
    lines.push(`Total Equity,${this.formatCurrency(report.equity.total)}`);
    lines.push(`Liabilities + Equity,${this.formatCurrency(report.liabilities.total + report.equity.total)}`);
    lines.push(`Balanced,${report.accountingEquationBalanced ? 'Yes' : 'No'}`);

    return lines.join('\n');
  }

  /**
   * Export Cash Flow report to CSV
   */
  private static exportCashFlowToCSV(report: CashFlowReport): string {
    const lines: string[] = [];

    // Metadata rows
    lines.push('Cash Flow Report');
    lines.push(`Period,${this.formatDate(report.period.startDate)} to ${this.formatDate(report.period.endDate)}`);
    lines.push(`Generated At,${this.formatDateTime(report.generatedAt)}`);
    lines.push(`Generated By,${report.generatedBy}`);
    if (report.departmentId) {
      lines.push(`Department,${report.departmentId}`);
    }
    lines.push(''); // Empty line

    // Operating Activities
    lines.push('OPERATING ACTIVITIES');
    lines.push('Category,Amount');
    lines.push(`Inflows,${this.formatCurrency(report.operatingActivities.inflows.total)}`);
    lines.push(`Outflows,${this.formatCurrency(report.operatingActivities.outflows.total)}`);
    lines.push(`Net Operating Cash Flow,${this.formatCurrency(report.operatingActivities.net)}`);
    lines.push(''); // Empty line

    // Investing Activities
    lines.push('INVESTING ACTIVITIES');
    lines.push('Category,Amount');
    lines.push(`Inflows,${this.formatCurrency(report.investingActivities.inflows.total)}`);
    lines.push(`Outflows,${this.formatCurrency(report.investingActivities.outflows.total)}`);
    lines.push(`Net Investing Cash Flow,${this.formatCurrency(report.investingActivities.net)}`);
    lines.push(''); // Empty line

    // Financing Activities
    lines.push('FINANCING ACTIVITIES');
    lines.push('Category,Amount');
    lines.push(`Inflows,${this.formatCurrency(report.financingActivities.inflows.total)}`);
    lines.push(`Outflows,${this.formatCurrency(report.financingActivities.outflows.total)}`);
    lines.push(`Net Financing Cash Flow,${this.formatCurrency(report.financingActivities.net)}`);
    lines.push(''); // Empty line

    // Summary
    lines.push('SUMMARY');
    lines.push('Metric,Amount');
    lines.push(`Beginning Cash Balance,${this.formatCurrency(report.beginningCash)}`);
    lines.push(`Net Operating Cash Flow,${this.formatCurrency(report.operatingActivities.net)}`);
    lines.push(`Net Investing Cash Flow,${this.formatCurrency(report.investingActivities.net)}`);
    lines.push(`Net Financing Cash Flow,${this.formatCurrency(report.financingActivities.net)}`);
    lines.push(`Total Net Cash Flow,${this.formatCurrency(report.netCashFlow)}`);
    lines.push(`Ending Cash Balance,${this.formatCurrency(report.endingCash)}`);

    return lines.join('\n');
  }

  /**
   * Format currency value
   */
  private static formatCurrency(value: number): string {
    if (value === null || value === undefined) {
      return '0.00';
    }
    
    // Format with thousand separators and 2 decimal places
    return value.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
  }

  /**
   * Format percentage value
   */
  private static formatPercentage(value: number): string {
    if (value === null || value === undefined) {
      return '0.0%';
    }
    
    return `${value.toFixed(1)}%`;
  }

  /**
   * Format date (YYYY-MM-DD)
   */
  private static formatDate(dateString: string): string {
    if (!dateString) {
      return '';
    }
    
    const date = new Date(dateString);
    return date.toISOString().split('T')[0];
  }

  /**
   * Format date and time
   */
  private static formatDateTime(dateString: string): string {
    if (!dateString) {
      return '';
    }
    
    const date = new Date(dateString);
    return date.toISOString().replace('T', ' ').split('.')[0];
  }

  /**
   * Escape CSV value (handle commas, quotes, newlines)
   */
  private static escapeCSVValue(value: string | number | null | undefined): string {
    if (value === null || value === undefined) {
      return '';
    }
    
    const stringValue = String(value);
    
    // If value contains comma, quote, or newline, wrap in quotes and escape quotes
    if (stringValue.includes(',') || stringValue.includes('"') || stringValue.includes('\n')) {
      return `"${stringValue.replace(/"/g, '""')}"`;
    }
    
    return stringValue;
  }

  /**
   * Get filename for export
   */
  static getFilename(reportType: string, startDate?: string, endDate?: string): string {
    const timestamp = new Date().toISOString().split('T')[0];
    const dateRange = startDate && endDate ? `_${startDate}_to_${endDate}` : '';
    return `${reportType}_report${dateRange}_${timestamp}.csv`;
  }
}
