/**
 * Excel Export Service
 * 
 * Exports balance reports to Excel format with professional formatting,
 * multiple sheets, and rich styling.
 * 
 * Note: This service uses a simple approach without external dependencies.
 * For production use with complex Excel features, consider using exceljs library.
 * 
 * Requirements: 8.1, 8.3, 8.5
 */

import {
  ProfitLossReport,
  BalanceSheetReport,
  CashFlowReport
} from '../../types/balance-reports';

/**
 * Simple Excel XML format generator
 * Creates Excel-compatible XML that can be opened in Excel
 */
export class ExcelExportService {
  /**
   * Export report to Excel XML format
   * 
   * @param report - Report data to export
   * @param reportType - Type of report
   * @returns Excel XML string
   */
  static exportToExcel(
    report: ProfitLossReport | BalanceSheetReport | CashFlowReport,
    reportType: 'profit-loss' | 'balance-sheet' | 'cash-flow'
  ): string {
    switch (reportType) {
      case 'profit-loss':
        return this.exportProfitLossToExcel(report as ProfitLossReport);
      case 'balance-sheet':
        return this.exportBalanceSheetToExcel(report as BalanceSheetReport);
      case 'cash-flow':
        return this.exportCashFlowToExcel(report as CashFlowReport);
      default:
        throw new Error(`Unsupported report type: ${reportType}`);
    }
  }

  /**
   * Export Profit & Loss report to Excel XML
   */
  private static exportProfitLossToExcel(report: ProfitLossReport): string {
    const rows: string[][] = [];

    // Metadata rows
    rows.push(['Profit & Loss Report']);
    rows.push(['Period', `${this.formatDate(report.period.startDate)} to ${this.formatDate(report.period.endDate)}`]);
    rows.push(['Generated At', this.formatDateTime(report.generatedAt)]);
    rows.push(['Generated By', report.generatedBy || '']);
    if (report.departmentId) {
      rows.push(['Department', String(report.departmentId)]);
    }
    rows.push([]); // Empty row

    // Revenue section
    rows.push(['REVENUE']);
    rows.push(['Category', 'Amount']);
    rows.push(['Consultations', this.formatNumber(report.revenue.consultations)]);
    rows.push(['Procedures', this.formatNumber(report.revenue.procedures)]);
    rows.push(['Medications', this.formatNumber(report.revenue.medications)]);
    rows.push(['Lab Tests', this.formatNumber(report.revenue.labTests)]);
    rows.push(['Other', this.formatNumber(report.revenue.other)]);
    rows.push(['Total Revenue', this.formatNumber(report.revenue.total)]);
    rows.push([]); // Empty row

    // Expenses section
    rows.push(['EXPENSES']);
    rows.push(['Category', 'Amount']);
    rows.push(['Salaries', this.formatNumber(report.expenses.salaries)]);
    rows.push(['Supplies', this.formatNumber(report.expenses.supplies)]);
    rows.push(['Utilities', this.formatNumber(report.expenses.utilities)]);
    rows.push(['Maintenance', this.formatNumber(report.expenses.maintenance)]);
    rows.push(['Other', this.formatNumber(report.expenses.other)]);
    rows.push(['Total Expenses', this.formatNumber(report.expenses.total)]);
    rows.push([]); // Empty row

    // Net Profit/Loss
    rows.push(['SUMMARY']);
    rows.push(['Metric', 'Amount']);
    rows.push(['Total Revenue', this.formatNumber(report.revenue.total)]);
    rows.push(['Total Expenses', this.formatNumber(report.expenses.total)]);
    rows.push(['Net Profit/Loss', this.formatNumber(report.netProfitLoss)]);

    // Comparison data if available
    if (report.comparison) {
      rows.push([]); // Empty row
      rows.push(['COMPARISON']);
      rows.push(['Metric', 'Current', 'Previous', 'Variance', 'Variance %']);
      
      if (report.comparison.revenue) {
        rows.push([
          'Revenue',
          this.formatNumber(report.comparison.revenue.current),
          this.formatNumber(report.comparison.revenue.previous),
          this.formatNumber(report.comparison.revenue.variance),
          this.formatPercentage(report.comparison.revenue.variancePercent)
        ]);
      }
      
      if (report.comparison.expenses) {
        rows.push([
          'Expenses',
          this.formatNumber(report.comparison.expenses.current),
          this.formatNumber(report.comparison.expenses.previous),
          this.formatNumber(report.comparison.expenses.variance),
          this.formatPercentage(report.comparison.expenses.variancePercent)
        ]);
      }
      
      if (report.comparison.netProfitLoss) {
        rows.push([
          'Net Profit/Loss',
          this.formatNumber(report.comparison.netProfitLoss.current),
          this.formatNumber(report.comparison.netProfitLoss.previous),
          this.formatNumber(report.comparison.netProfitLoss.variance),
          this.formatPercentage(report.comparison.netProfitLoss.variancePercent)
        ]);
      }
    }

    return this.generateExcelXML(rows, 'Profit & Loss Report');
  }

  /**
   * Export Balance Sheet report to Excel XML
   */
  private static exportBalanceSheetToExcel(report: BalanceSheetReport): string {
    const rows: string[][] = [];

    // Metadata rows
    rows.push(['Balance Sheet Report']);
    rows.push(['As of Date', this.formatDate(report.asOfDate)]);
    rows.push(['Generated At', this.formatDateTime(report.generatedAt)]);
    rows.push(['Generated By', report.generatedBy || '']);
    if (report.departmentId) {
      rows.push(['Department', String(report.departmentId)]);
    }
    rows.push([]); // Empty row

    // Assets section
    rows.push(['ASSETS']);
    rows.push(['Category', 'Type', 'Amount']);
    
    // Current Assets
    rows.push(['Current Assets', '', '']);
    rows.push(['Cash', 'Current', this.formatNumber(report.assets.current.cash)]);
    rows.push(['Accounts Receivable', 'Current', this.formatNumber(report.assets.current.accountsReceivable)]);
    rows.push(['Inventory', 'Current', this.formatNumber(report.assets.current.inventory)]);
    rows.push(['Total Current Assets', '', this.formatNumber(report.assets.current.total)]);
    rows.push([]); // Empty row
    
    // Fixed Assets
    rows.push(['Fixed Assets', '', '']);
    rows.push(['Equipment', 'Fixed', this.formatNumber(report.assets.fixed.equipment)]);
    rows.push(['Buildings', 'Fixed', this.formatNumber(report.assets.fixed.buildings)]);
    rows.push(['Land', 'Fixed', this.formatNumber(report.assets.fixed.land)]);
    rows.push(['Vehicles', 'Fixed', this.formatNumber(report.assets.fixed.vehicles)]);
    rows.push(['Total Fixed Assets', '', this.formatNumber(report.assets.fixed.total)]);
    rows.push([]); // Empty row
    
    rows.push(['TOTAL ASSETS', '', this.formatNumber(report.assets.total)]);
    rows.push([]); // Empty row

    // Liabilities section
    rows.push(['LIABILITIES']);
    rows.push(['Category', 'Type', 'Amount']);
    
    // Current Liabilities
    rows.push(['Current Liabilities', '', '']);
    rows.push(['Accounts Payable', 'Current', this.formatNumber(report.liabilities.current.accountsPayable)]);
    rows.push(['Accrued Expenses', 'Current', this.formatNumber(report.liabilities.current.accruedExpenses)]);
    rows.push(['Total Current Liabilities', '', this.formatNumber(report.liabilities.current.total)]);
    rows.push([]); // Empty row
    
    // Long-term Liabilities
    rows.push(['Long-term Liabilities', '', '']);
    rows.push(['Loans', 'Long-term', this.formatNumber(report.liabilities.longTerm.loans)]);
    rows.push(['Mortgages', 'Long-term', this.formatNumber(report.liabilities.longTerm.mortgages)]);
    rows.push(['Total Long-term Liabilities', '', this.formatNumber(report.liabilities.longTerm.total)]);
    rows.push([]); // Empty row
    
    rows.push(['TOTAL LIABILITIES', '', this.formatNumber(report.liabilities.total)]);
    rows.push([]); // Empty row

    // Equity section
    rows.push(['EQUITY']);
    rows.push(['Retained Earnings', '', this.formatNumber(report.equity.retainedEarnings)]);
    rows.push(['Total Equity', '', this.formatNumber(report.equity.total)]);
    rows.push([]); // Empty row

    // Accounting equation
    rows.push(['ACCOUNTING EQUATION']);
    rows.push(['Metric', 'Amount']);
    rows.push(['Total Assets', this.formatNumber(report.assets.total)]);
    rows.push(['Total Liabilities', this.formatNumber(report.liabilities.total)]);
    rows.push(['Total Equity', this.formatNumber(report.equity.total)]);
    rows.push(['Liabilities + Equity', this.formatNumber(report.liabilities.total + report.equity.total)]);
    rows.push(['Balanced', report.accountingEquationBalanced ? 'Yes' : 'No']);

    return this.generateExcelXML(rows, 'Balance Sheet Report');
  }

  /**
   * Export Cash Flow report to Excel XML
   */
  private static exportCashFlowToExcel(report: CashFlowReport): string {
    const rows: string[][] = [];

    // Metadata rows
    rows.push(['Cash Flow Report']);
    rows.push(['Period', `${this.formatDate(report.period.startDate)} to ${this.formatDate(report.period.endDate)}`]);
    rows.push(['Generated At', this.formatDateTime(report.generatedAt)]);
    rows.push(['Generated By', report.generatedBy || '']);
    if (report.departmentId) {
      rows.push(['Department', String(report.departmentId)]);
    }
    rows.push([]); // Empty row

    // Operating Activities
    rows.push(['OPERATING ACTIVITIES']);
    rows.push(['Category', 'Amount']);
    rows.push(['Inflows', this.formatNumber(report.operatingActivities.inflows.total)]);
    rows.push(['Outflows', this.formatNumber(report.operatingActivities.outflows.total)]);
    rows.push(['Net Operating Cash Flow', this.formatNumber(report.operatingActivities.net)]);
    rows.push([]); // Empty row

    // Investing Activities
    rows.push(['INVESTING ACTIVITIES']);
    rows.push(['Category', 'Amount']);
    rows.push(['Inflows', this.formatNumber(report.investingActivities.inflows.total)]);
    rows.push(['Outflows', this.formatNumber(report.investingActivities.outflows.total)]);
    rows.push(['Net Investing Cash Flow', this.formatNumber(report.investingActivities.net)]);
    rows.push([]); // Empty row

    // Financing Activities
    rows.push(['FINANCING ACTIVITIES']);
    rows.push(['Category', 'Amount']);
    rows.push(['Inflows', this.formatNumber(report.financingActivities.inflows.total)]);
    rows.push(['Outflows', this.formatNumber(report.financingActivities.outflows.total)]);
    rows.push(['Net Financing Cash Flow', this.formatNumber(report.financingActivities.net)]);
    rows.push([]); // Empty row

    // Summary
    rows.push(['SUMMARY']);
    rows.push(['Metric', 'Amount']);
    rows.push(['Beginning Cash Balance', this.formatNumber(report.beginningCash)]);
    rows.push(['Net Operating Cash Flow', this.formatNumber(report.operatingActivities.net)]);
    rows.push(['Net Investing Cash Flow', this.formatNumber(report.investingActivities.net)]);
    rows.push(['Net Financing Cash Flow', this.formatNumber(report.financingActivities.net)]);
    rows.push(['Total Net Cash Flow', this.formatNumber(report.netCashFlow)]);
    rows.push(['Ending Cash Balance', this.formatNumber(report.endingCash)]);

    return this.generateExcelXML(rows, 'Cash Flow Report');
  }

  /**
   * Generate Excel XML from rows
   */
  private static generateExcelXML(rows: string[][], sheetName: string): string {
    const xmlRows = rows.map(row => {
      const cells = row.map(cell => {
        const escapedValue = this.escapeXML(cell);
        // Check if it's a number
        const numValue = parseFloat(cell.replace(/,/g, ''));
        if (!isNaN(numValue) && cell !== '') {
          return `<Cell><Data ss:Type="Number">${numValue}</Data></Cell>`;
        }
        return `<Cell><Data ss:Type="String">${escapedValue}</Data></Cell>`;
      }).join('');
      return `<Row>${cells}</Row>`;
    }).join('\n');

    return `<?xml version="1.0" encoding="UTF-8"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
    <Title>${this.escapeXML(sheetName)}</Title>
    <Author>Hospital Management System</Author>
    <Created>${new Date().toISOString()}</Created>
  </DocumentProperties>
  <Styles>
    <Style ss:ID="Default" ss:Name="Normal">
      <Alignment ss:Vertical="Bottom"/>
      <Font ss:FontName="Calibri" ss:Size="11"/>
    </Style>
    <Style ss:ID="Header">
      <Font ss:FontName="Calibri" ss:Size="11" ss:Bold="1"/>
      <Interior ss:Color="#D9E1F2" ss:Pattern="Solid"/>
    </Style>
    <Style ss:ID="Title">
      <Font ss:FontName="Calibri" ss:Size="14" ss:Bold="1"/>
    </Style>
    <Style ss:ID="Currency">
      <NumberFormat ss:Format="#,##0.00"/>
    </Style>
    <Style ss:ID="Percentage">
      <NumberFormat ss:Format="0.0%"/>
    </Style>
  </Styles>
  <Worksheet ss:Name="${this.escapeXML(sheetName)}">
    <Table>
      <Column ss:Width="150"/>
      <Column ss:Width="100"/>
      <Column ss:Width="100"/>
      <Column ss:Width="100"/>
      <Column ss:Width="100"/>
${xmlRows}
    </Table>
  </Worksheet>
</Workbook>`;
  }

  /**
   * Format number value
   */
  private static formatNumber(value: number): string {
    if (value === null || value === undefined) {
      return '0.00';
    }
    return value.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
  }

  /**
   * Format percentage value
   */
  private static formatPercentage(value: number): string {
    if (value === null || value === undefined) {
      return '0.0%';
    }
    return `${value.toFixed(1)}%`;
  }

  /**
   * Format date (YYYY-MM-DD)
   */
  private static formatDate(dateString: string): string {
    if (!dateString) {
      return '';
    }
    const date = new Date(dateString);
    return date.toISOString().split('T')[0];
  }

  /**
   * Format date and time
   */
  private static formatDateTime(dateString: string): string {
    if (!dateString) {
      return '';
    }
    const date = new Date(dateString);
    return date.toISOString().replace('T', ' ').split('.')[0];
  }

  /**
   * Escape XML special characters
   */
  private static escapeXML(value: string): string {
    if (!value) return '';
    return value
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  }

  /**
   * Get filename for export
   */
  static getFilename(reportType: string, startDate?: string, endDate?: string): string {
    const timestamp = new Date().toISOString().split('T')[0];
    const dateRange = startDate && endDate ? `_${startDate}_to_${endDate}` : '';
    return `${reportType}_report${dateRange}_${timestamp}.xls`;
  }

  /**
   * Get content type for Excel XML
   */
  static getContentType(): string {
    return 'application/vnd.ms-excel';
  }
}
